create table cards (
card_id serial primary key, 
value varchar(3),
suit varchar(10), 
color varchar(5)
);

create table users (
user_id serial primary key, 
username varchar,
password varchar
)

insert into cards (value, suit, color)
values  ('2','heart','red'),
        ('2','diamond','red'),
        ('2','spade','black'),
        ('2','club','black'),
        ('3','heart','red'),
        ('3','diamond','red'),
        ('3','spade','black'),
        ('3','club','black'),
        ('4','heart','red'),
        ('4','diamond','red'),
        ('4','spade','black'),
        ('4','club','black'),
        ('5','heart','red'),
        ('5','diamond','red'),
        ('5','spade','black'),
        ('5','club','black'),
         ('6','heart','red'),
        ('6','diamond','red'),
        ('6','spade','black'),
        ('6','club','black'),
         ('7','heart','red'),
        ('7','diamond','red'),
        ('7','spade','black'),
        ('7','club','black'),
         ('8','heart','red'),
        ('8','diamond','red'),
        ('8','spade','black'),
        ('8','club','black'),
         ('9','heart','red'),
        ('9','diamond','red'),
        ('9','spade','black'),
        ('9','club','black'),
         ('10','heart','red'),
        ('10','diamond','red'),
        ('10','spade','black'),
        ('10','club','black'),
         ('J','heart','red'),
        ('J','diamond','red'),
        ('J','spade','black'),
        ('J','club','black'),
         ('Q','heart','red'),
        ('Q','diamond','red'),
        ('Q','spade','black'),
        ('Q','club','black'),
         ('K','heart','red'),
        ('K','diamond','red'),
        ('K','spade','black'),
        ('K','club','black'),
         ('A','heart','red'),
        ('A','diamond','red'),
        ('A','spade','black'),
        ('A','club','black');

